/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_exlmoto_spout_SpoutNativeLibProxy */

#ifndef _Included_ru_exlmoto_spout_SpoutNativeLibProxy
#define _Included_ru_exlmoto_spout_SpoutNativeLibProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutNativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutNativeInit
  (JNIEnv *, jclass);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutNativeDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutNativeDeinit
  (JNIEnv *, jclass);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutNativeSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutNativeSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutNativeDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutNativeDraw
  (JNIEnv *, jclass);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutNativeKeyDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutNativeKeyDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutNativeKeyUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutNativeKeyUp
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutFilter
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutFilter
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutNativePushScore
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutNativePushScore
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutVibrate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutVibrate
  (JNIEnv *, jclass);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutSetSound
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutSetSound
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutGetScoreScores
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutGetScoreScores
  (JNIEnv *, jclass);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutGetScoreHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutGetScoreHeight
  (JNIEnv *, jclass);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutDisplayOffsetX
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutDisplayOffsetX
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutDisplayOffsetY
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutDisplayOffsetY
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_exlmoto_spout_SpoutNativeLibProxy
 * Method:    SpoutInitilizeGlobalJavaEnvPointer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_spout_SpoutNativeLibProxy_SpoutInitilizeGlobalJavaEnvPointer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
