######################################################################
# Automatically generated by qmake (3.0) ?? ???. 15 02:05:59 2015
######################################################################

CONFIG -= qt

TEMPLATE = app
TARGET = Spout
INCLUDEPATH += .

QMAKE_CFLAGS = $$system(sdl-config --cflags)
LIBS = $$system(sdl-config --libs) -lGL -lGLU

# Input
HEADERS += config.h font.h piece.h sintable.h \
    spout.h
SOURCES += piece.c spout.c
